[project]
name = "yars"
version = "0.1.0"
description = "YARS (Yet Another Reddit Scraper)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "meta-ai-api>=1.2.5",
    "pygments>=2.19.1",
 "requests>=2.32.3",
]
